### ISSUE TITLE
Oscam not install 

### ISSUE THREAD

**Issue by GazKez** [d-two/hassio-addons#1]
Hi d-two, i used oscam with your addon during months, but i have to reinstall and doesn´t work. Seems something changed with new home assistant versions. Can you help us to work again? Thanks in advanced!!

`The command '/bin/ash -o pipefail -c echo "**** install build packages ****" && apk add --no-cache --virtual=build-dependencies gcc g++ libusb-dev linux-headers make openssl-dev pcsc-lite-dev subversion tar shadow && echo "**** install runtime packages ****" && apk add --no-cache ccid curl libcrypto1.1 libssl1.1 libusb pcsc-lite pcsc-lite-libs && echo "**** compile oscam ****" && if [ -z ${OSCAM_VERSION+x} ]; then OSCAM_VERSION=$(svn info --show-item revision https://svn.streamboard.tv/oscam/trunk ); fi && svn checkout https://svn.streamboard.tv/oscam/trunk@${OSCAM_VERSION} /tmp/oscam-svn && cd /tmp/oscam-svn && ./config.sh --enable all --disable CARDREADER_DB2COM CARDREADER_INTERNAL CARDREADER_STINGER CARDREADER_STAPI CARDREADER_STAPI5 IPV6SUPPORT LCDSUPPORT LEDSUPPORT READ_SDT_CHARSETS && make CONF_DIR=/config DEFAULT_PCSC_FLAGS="-I/usr/include/PCSC" NO_PLUS_TARGET=1 OSCAM_BIN=/usr/bin/oscam pcsc-libusb && echo "**** fix broken permissions from pcscd install ****" && chown root:root /usr/sbin/pcscd && chmod 755 /usr/sbin/pcscd && echo "**** install PCSC drivers ****" && mkdir -p /tmp/omnikey && curl -o /tmp/omnikey.tar.gz -L https://www.hidglobal.com/sites/default/files/drivers/ifdokccid_linux_x86_64-v4.2.8.tar.gz && tar xzf /tmp/omnikey.tar.gz -C /tmp/omnikey --strip-components=2 && cd /tmp/omnikey && ./install && echo "**** create abc user and make our folders ****" && groupmod -g 1000 users && useradd -u 911 -U -d /config -s /bin/false abc && usermod -G users abc && echo "**** fix group for card readers and add abc to dialout group ****" && groupmod -g 24 cron && groupmod -g 16 dialout && usermod -a -G 16 abc && echo "**** cleanup ****" && apk del --purge build-dependencies && rm -rf /tmp/*' returned a non-zero code: 2`

![chrome_3M3pZxAVvX](https://user-images.githubusercontent.com/55027773/200114859-c417c1c2-803a-491d-b95b-6e5fbe9dfc20.png)

**Comment by d-two** [comment]
Which arch is your system? (Aarch64, x86)

**Comment by GazKez** [comment]
Hi, i use a Raspberry Pi 4 and a virtual machine (ova), i try in the two system and the problem is the same. Thank you in advanced for your help!

**Comment by d-two** [comment]
I think now is fixed
