### ISSUE TITLE
Baikal (add-on  HAOS):  PHP version issue

### ISSUE THREAD

**Issue by paindaveine** [d-two/hassio-addons#5]
Hi. I just added Baikal as add-on on Home Assistant (HAOS Raspberry 5 12.1 - 2024.3.3 ). When I try to access the GUI, I have this error message: 

Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".  I tried to "rebuild" add-on  and restart it, same error.

Phpmyadmin add-on is running fine and report PHP version 8.1.27

Thanks in advance for any help... 

Log is:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh

-----------------------------------------------------------
 Add-on: Baikal
 Baikal is a Cal and CardDAV server, based on sabre/dav, that includes an administrative interface for easy management.
-----------------------------------------------------------
 Add-on version: 0.9.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.1  (aarch64 / raspberrypi5-64)
 Home Assistant Core: 2024.3.3
 Home Assistant Supervisor: 2024.03.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/baikal.sh
cont-init: info: /etc/cont-init.d/baikal.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
[11:25:11] INFO: Starting PHP-FPM...
[11:25:12] INFO: Starting NGinx....
2024/03/26 11:26:11 [error] 210#210: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.30. in /data/vendor/composer/platform_check.php on line 24" while reading response header from upstream, client: 192.168.0.88, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.0.129:8013"`

**Comment by d-two** [comment]
Fixed
